import './globals.css'
import { Inter } from 'next/font/google'
import Noise from "./components/noise";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Joona Kareinen',
  description: 'Generated by create next app',
  description: 'Joona Kareinen\'s portfolio showcasing expertise in Computer Vision, Artificial Intelligence, and Data Science.',
  keywords: 'Portfolio, Computer Vision, Artificial Intelligence, Data Science, Master of Science',
  author: 'Joona Kareinen',
  metadataBase: new URL('https://jookare.vercel.app/'),
  charset: 'UTF-8',
  openGraph: {
    title: 'Joona Kareinen',
    description: 'Explore Joona Kareinen\'s portfolio website.',
    type: 'website',
    locale: 'en_FI',
    site_name: 'Joona Kareinen Portfolio',
    images: [
      {
        url: '/Logo.png',
        width: 1080,
        height: 950,
        alt: 'Joona Kareinen Portfolio Logo',
      },
    ],
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-[#141414] overflow-x-hidden'>
      <body className={inter.className}>
        <Noise />
        {children}
      </body>
    </html>
  )
}
